----------------------- BAI 1 ---------------------------------
CREATE DATABASE QLBH
CREATE TABLE KHACHHANG
(
	MAKH CHAR(4) PRIMARY KEY, 
	HOTEN VARCHAR(40) NOT NULL,
	DCHI VARCHAR(50) NOT NULL,
	SODT VARCHAR(20) NOT NULL,
	NGSINH SMALLDATETIME,
	NGDK SMALLDATETIME,
	DOANHSO MONEY NOT NULL
)

CREATE TABLE NHANVIEN
(
	MANV CHAR(4) NOT NULL,
	HOTEN VARCHAR(40),
	SODT VARCHAR(20),
	NGVL smalldatetime
)

CREATE TABLE SANPHAM
(
	MASP CHAR(4)  NOT NULL,
	TENSP VARCHAR(40),
	DVT VARCHAR(20),
	NUOCSX VARCHAR(40),
	GIA money,
)

CREATE TABLE HOADON
(
	SOHD int NOT NULL,
	NGHD smalldatetime,
	MAKH CHAR(4),
	MANV CHAR(4),
	TRIGIA	money
)

CREATE TABLE CTHD
(
	SOHD int NOT NULL,
	MASP CHAR(4) NOT NULL,
	CONSTRAINT PK_CTHD
	PRIMARY KEY (SOHD,MASP),
	SL int,
	
)

--------KHOA NGOAI--------
ALTER TABLE CTHD ADD
CONSTRAINT FK_CTHD_HD FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
CONSTRAINT FK_CTHD_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)


ALTER TABLE HOADON ADD
CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)




--------KHOA CHINH--------
ALTER TABLE KHACHHANG 
ADD CONSTRAINT PK_KH PRIMARY KEY (MAKH)

ALTER TABLE HOADON 
ADD CONSTRAINT PK_HD PRIMARY KEY (SOHD)

ALTER TABLE SANPHAM 
ADD CONSTRAINT PK_SP PRIMARY KEY (MASP)

ALTER TABLE NHANVIEN 
ADD CONSTRAINT PK_NV PRIMARY KEY (MANV)

--------CAU 2--------
ALTER TABLE SANPHAM
ADD GHICHU VARCHAR(20)

--------CAU 3--------
ALTER TABLE KHACHHANG
ADD LOAIKH tinyint;

ALTER TABLE KHACHHANG
ALTER COLUMN LOAIKH VARCHAR(50)

--------CAU 4--------
ALTER TABLE SANPHAM
ALTER COLUMN GHICHU VARCHAR(100);

--------CAU 5--------
ALTER TABLE SANPHAM
DROP COLUMN GHICHU;

--------CAU 6--------
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_LOAIKH CHECK (LOAIKH IN ('Vang lai', 'Thuong xuyen', 'VIP', 'The vang'));

--------CAU 7--------
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_DONVITINH CHECK (DVT IN ('cay', 'hop', 'cai', 'quyen', 'chuc'));

--------CAU 8--------
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_GIABAN CHECK (GIA >= 500);

--------CAU 9--------
ALTER TABLE CTHD
ADD CONSTRAINT CK_SOLUONG CHECK (SL >= 1);

--------CAU 10--------
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_NGAYDANGKY CHECK (NGDK > NGSINH);



-----------------------------------------------------BAI 2--------------------------------------------------------------------
CREATE DATABASE QLGV

CREATE TABLE KHOA
(
	MAKHOA	varchar(4) NOT NULL,
	TENKHOA	varchar(40),
	NGTLAP	smalldatetime,
	TRGKHOA	char(4)
)

CREATE TABLE MONHOC
(
	MAMH	varchar(10) NOT NULL,
	TENMH	varchar(40),
	TCLT	tinyint,
	TCTH	tinyint,
	MAKHOA	varchar(4)
)

CREATE TABLE DIEUKIEN
(
	MAMH		varchar(10) NOT NULL,
	MAMH_TRUOC	varchar(10) NOT NULL
)

CREATE TABLE GIAOVIEN
(
	MAGV		char(4) NOT NULL,
	HOTEN		varchar(40),
	HOCVI		varchar(10),
	HOCHAM		varchar(10),
	GIOITINH	varchar(3),
	NGSINH		smalldatetime,
	NGVL		smalldatetime,
	HESO		numeric(4,2),
	MUCLUONG	money,
	MAKHOA		varchar(4)
)

CREATE TABLE LOP
(
	MALOP		char(3) NOT NULL,
	TENLOP		varchar(40),
	TRGLOP		char(5),
	SISO		tinyint,
	MAGVCN		char(4)
)

CREATE TABLE HOCVIEN
(
	MAHV		char(5) NOT NULL,
	HO			varchar(40),
	TEN			varchar(10),
	NGSINH		smalldatetime,
	GIOITINH	varchar(3),
	NOISINH		varchar(40),
	MALOP		char(3)
)

CREATE TABLE GIANGDAY
(
	MALOP	char(3) NOT NULL,
	MAMH	varchar(10) NOT NULL,
	MAGV	char(4),
	HOCKY	tinyint,
	NAM		smallint,
	TUNGAY smalldatetime,
	DENNGAY	smalldatetime
)

CREATE TABLE KETQUATHI
(
	MAHV	char(5) NOT NULL,
	MAMH	varchar(10) NOT NULL,
	LANTHI  tinyint NOT NULL,
	NGTHI	smalldatetime,
	DIEM	numeric(4,2),
	KQUA	varchar(10)
)
--------KHOA CHINH--------
ALTER TABLE DIEUKIEN 
ADD CONSTRAINT PK_DK PRIMARY KEY (MAMH,MAMH_TRUOC)

ALTER TABLE GIANGDAY 
ADD CONSTRAINT PK_GD PRIMARY KEY (MAMH,MALOP)

ALTER TABLE GIAOVIEN 
ADD CONSTRAINT PK_GV PRIMARY KEY (MAGV)

ALTER TABLE HOCVIEN 
ADD CONSTRAINT PK_HV PRIMARY KEY (MAHV)

ALTER TABLE KETQUATHI 
ADD CONSTRAINT PK_KQT PRIMARY KEY (MAHV,MAMH,LANTHI)

ALTER TABLE KHOA 
ADD CONSTRAINT PK_K PRIMARY KEY (MAKHOA)

ALTER TABLE LOP 
ADD CONSTRAINT PK_L PRIMARY KEY (MALOP)

ALTER TABLE MONHOC 
ADD CONSTRAINT PK_MH PRIMARY KEY (MAMH)

--------KHOA NGOAI--------
ALTER TABLE LOP 
ADD CONSTRAINT FK_LOP_TL FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN(MAHV)

ALTER TABLE KHOA 
ADD CONSTRAINT FK_KHOA_TK FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV)

--------CAU 1--------
ALTER TABLE HOCVIEN 
ADD GHICHU VARCHAR(20), DIEMTB int, XEPLOAI char(4)

--------CAU 3--------
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CK_GT CHECK (GIOITINH IN ('NAM','NU'))

ALTER TABLE HOCVIEN
ADD CONSTRAINT CK_GTHV CHECK (GIOITINH IN ('NAM','NU'))

--------CAU 4--------
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_DIEMTHI CHECK (DIEM BETWEEN 0 AND 10)

--------CAU 5--------
SELECT MAHV, Diem,
       CASE WHEN Diem >= 5 THEN 'Dat'
            ELSE 'Khong dat'
       END AS KQUA
FROM KETQUATHI

--------CAU 6--------
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_LT CHECK(LANTHI BETWEEN 0 AND 3)

--------CAU 7--------
ALTER TABLE GIANGDAY
ADD CONSTRAINT CK_HK CHECK (HOCKY BETWEEN 1 AND 3)


--------CAU 8--------
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CK_HOCVI CHECK(HOCVI IN ('CN','KS','THS','TS','PTS'))