--------------LAB 3----------------
-----------------------------------------QLBH-------------------------------------------
-------CAU 12--------
SELECT SOHD
FROM CTHD
WHERE  (MASP='BB01' AND  (SL BETWEEN 10 AND 20)) OR ( MASP ='BB02' AND (SL BETWEEN 10 AND 20))

-------CAU 13--------
SELECT SOHD
FROM CTHD
WHERE  (MASP='BB01' AND  (SL BETWEEN 10 AND 20)) 
INTERSECT
		SELECT SOHD
			FROM CTHD
			WHERE MASP ='BB02' AND (SL BETWEEN 10 AND 20)

-------CAU 14--------
SELECT MASP,TENSP
FROM SANPHAM
WHERE NUOCSX ='Trung Quoc'
UNION
SELECT SP.MASP,TENSP
FROM SANPHAM SP, HOADON HD,CTHD
WHERE SP.MASP=CTHD.MASP AND CTHD.SOHD=HD.SOHD AND NGHD='1/1/2007'


-------CAU 15--------
SELECT SP.MASP,TENSP
FROM SANPHAM SP
WHERE NOT EXISTS (SELECT * 
				FROM CTHD			
				WHERE CTHD.MASP = SP.MASP)

				
-------CAU 16--------
SELECT SP.MASP,TENSP
FROM SANPHAM SP
WHERE NOT EXISTS (SELECT * 
				FROM CTHD,HOADON HD
				WHERE CTHD.MASP = SP.MASP AND CTHD.SOHD = HD.SOHD AND YEAR(NGHD) = 2006)

				
-------CAU 17--------
SELECT SP.MASP, TENSP
FROM SANPHAM SP
WHERE NUOCSX = 'Trung Quoc' AND NOT EXISTS (SELECT *
											FROM CTHD, HOADON HD
											WHERE CTHD.MASP = SP.MASP AND CTHD.SOHD = HD.SOHD AND YEAR(NGHD) = 2006)

-------CAU 18--------
SELECT HD.SOHD
FROM HOADON HD,SANPHAM SP, CTHD
WHERE CTHD.MASP = SP.MASP AND CTHD.SOHD = HD.SOHD AND YEAR(NGHD) = 2006 AND NUOCSX='Singapore'
GROUP BY HD.SOHD
HAVING Count(SP.MASP) = (SELECT Count(SP.MASP)
						FROM SANPHAM SP
						WHERE NUOCSX='Singapore')

-----------------------------------------QLGV-------------------------------------------
---------CAU 1----------
UPDATE GIAOVIEN
SET HESO = HESO*1.2
WHERE MAGV IN (SELECT TRGKHOA 
				FROM KHOA)

---------CAU 2----------
UPDATE HV SET DIEMTB = DTB_HOCVIEN.DTB
FROM HOCVIEN HV LEFT JOIN (
SELECT MAHV, AVG(DIEM) AS DTB 
	FROM KETQUATHI A
	WHERE NOT EXISTS (
		SELECT 1 
		FROM KETQUATHI B 
		WHERE A.MAHV = B.MAHV AND A.MAMH = B.MAMH AND A.LANTHI < B.LANTHI
	) 
	GROUP BY MAHV
	) DTB_HOCVIEN
		ON HV.MAHV = DTB_HOCVIEN.MAHV

---------CAU 3----------
UPDATE HOCVIEN
SET GHICHU = 'Cam thi'
WHERE MAHV IN (SELECT MAHV
			FROM KETQUATHI
			WHERE  DIEM < 5 AND LANTHI =3
)

---------CAU 4----------
UPDATE HOCVIEN SET XEPLOAI = CASE 
	WHEN DIEMTB >= 9 THEN 'XS'
	WHEN DIEMTB >= 8 THEN 'G'
	WHEN DIEMTB >= 6.5 THEN 'K'
	WHEN DIEMTB >= 5 THEN 'TB'
	ELSE 'Y'
END

---------CAU 6----------
SELECT TENMH
FROM GIANGDAY GD, GIAOVIEN GV, MONHOC MH
WHERE GD.MAGV= GV.MAGV AND GV.HOTEN ='Tran Tam Thanh' AND GD.HOCKY=1 AND NAM = 2006 AND MH.MAKHOA = GV.MAKHOA

---------CAU 7----------
SELECT MAMH, TENMH FROM MONHOC
WHERE MAMH IN (
	SELECT  MAMH FROM GIANGDAY WHERE MAGV IN (
		SELECT MAGVCN FROM LOP WHERE MALOP = 'K11'
	) AND HOCKY = 1 AND NAM = 2006
)

---------CAU 8----------
SELECT HO+ ' ' + TEN AS HOTEN 
FROM HOCVIEN
WHERE MAHV IN (SELECT TRGLOP 
				FROM LOP 
				WHERE MALOP IN (SELECT MALOP
								FROM  GIAOVIEN GV, GIANGDAY GD, MONHOC MH
								WHERE GD.MAGV =GV.MAGV AND GV.HOTEN='Nguyen To Lan' AND MH.MAMH = GD.MAMH AND MH.TENMH = 'Co So Du Lieu')) 


---------CAU 9----------
SELECT MAMH, TENMH
FROM MONHOC MH
WHERE MAMH IN(SELECT MAMH_TRUOC
			FROM DIEUKIEN DK
			WHERE  MAMH IN (SELECT MAMH 
							FROM MONHOC
							WHERE TENMH = 'Co so du lieu' ))


---------CAU 10----------
SELECT MAMH, TENMH
FROM MONHOC MH
WHERE MAMH IN(SELECT MAMH
			FROM DIEUKIEN DK
			WHERE  MAMH_TRUOC IN (SELECT MAMH 
							FROM MONHOC
							WHERE TENMH = 'Cau Truc Roi Rac' ))


---------CAU 11----------
SELECT HOTEN
FROM GIAOVIEN GV
WHERE MAGV IN (SELECT MAGV
				FROM GIANGDAY GD
				WHERE HOCKY=1 AND NAM = 2006 AND MALOP IN('K11','K12') AND MAMH='CTRR'
				GROUP BY MAGV
				HAVING COUNT(DISTINCT MALOP) = 2
				)


---------CAU 12----------
SELECT MAHV,HO+''+TEN AS HOTEN
FROM HOCVIEN
WHERE MAHV IN (SELECT MAHV
				FROM KETQUATHI
				WHERE MAMH='CSDL' AND KQUA= 'Khong Dat' AND MAHV in (SELECT MAHV
																		FROM KETQUATHI
																		WHERE MAMH='CSDL'
																		GROUP BY MAHV
																		HAVING COUNT(LANTHI) = 1)
				)

---------CAU 13----------
SELECT MAGV, HOTEN 
FROM GIAOVIEN 
WHERE MAGV NOT IN (SELECT MAGV 
					FROM GIANGDAY
)

---------CAU 14----------
SELECT MAGV, HOTEN 
FROM GIAOVIEN GV
WHERE MAGV NOT IN (SELECT GV.MAGV 
					FROM GIAOVIEN GV, MONHOC MH,GIANGDAY GD
					WHERE GV.MAKHOA=MH.MAKHOA AND GD.MAGV=GV.MAGV AND GD.MAMH=MH.MAMH )

---------CAU 15----------
SELECT HO+''+TEN AS HOTEN,MAHV
FROM HOCVIEN
WHERE MALOP='K11' AND MAHV IN (SELECT MAHV 
								FROM KETQUATHI
								WHERE  KQUA='Khong Dat' AND MAHV IN(SELECT MAHV
																	FROM KETQUATHI
																	GROUP BY MAMH,MAHV
																	HAVING COUNT(LANTHI)=3)
								UNION
								SELECT MAHV 
								FROM KETQUATHI
								WHERE LANTHI=2 AND MAMH='CTRR' AND DIEM=5
								)
---------CAU 16----------
SELECT HOTEN FROM GIAOVIEN 
WHERE MAGV IN (
	SELECT MAGV FROM GIANGDAY 
	WHERE MAMH = 'CTRR'
	GROUP BY MAGV, HOCKY, NAM 
	HAVING COUNT(MALOP) >= 2
)

---------CAU 17----------
SELECT HV.MAHV, DIEM
FROM HOCVIEN HV, KETQUATHI KQ
WHERE KQ.MAHV=HV.MAHV AND MAMH='CSDL' AND LANTHI =(SELECT MAX(LANTHI)
				FROM KETQUATHI KQ
				WHERE MAMH='CSDL'AND KQ.MAHV=HV.MAHV
				)
ORDER BY HV.MAHV ASC

---------CAU 18----------
SELECT HV.MAHV, DIEM
FROM HOCVIEN HV, KETQUATHI KQ, MONHOC MH
WHERE KQ.MAHV=HV.MAHV AND MH.MAMH='CSDL' AND MH.MAMH = KQ.MAMH AND MH.TENMH='Co so du lieu' AND DIEM =(SELECT MAX(DIEM)
				FROM KETQUATHI KQ
				WHERE MAMH='CSDL'AND KQ.MAHV=HV.MAHV
				)
ORDER BY HV.MAHV ASC
